/* Generated By:JavaCC: Do not edit this line. DefaultInterpreterConstants.java */
package barebones.interpreter.parsers;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface DefaultInterpreterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOVE_CMD = 5;
  /** RegularExpression Id. */
  int INV_CMD = 6;
  /** RegularExpression Id. */
  int TIME_CMD = 7;
  /** RegularExpression Id. */
  int QUIT_CMD = 8;
  /** RegularExpression Id. */
  int SAVE_CMD = 9;
  /** RegularExpression Id. */
  int REST_CMD = 10;
  /** RegularExpression Id. */
  int DROP_CMD = 11;
  /** RegularExpression Id. */
  int OPEN_CMD = 12;
  /** RegularExpression Id. */
  int TAKE_CMD = 13;
  /** RegularExpression Id. */
  int EXAM_CMD = 14;
  /** RegularExpression Id. */
  int PUSH_CMD = 15;
  /** RegularExpression Id. */
  int PULL_CMD = 16;
  /** RegularExpression Id. */
  int SAY_CMD = 17;
  /** RegularExpression Id. */
  int NDIR = 18;
  /** RegularExpression Id. */
  int SDIR = 19;
  /** RegularExpression Id. */
  int EDIR = 20;
  /** RegularExpression Id. */
  int WDIR = 21;
  /** RegularExpression Id. */
  int UDIR = 22;
  /** RegularExpression Id. */
  int DDIR = 23;
  /** RegularExpression Id. */
  int ITEM_WORD = 24;
  /** RegularExpression Id. */
  int ID_CONCEPT = 25;
  /** RegularExpression Id. */
  int DOOR_TO_THE = 26;
  /** RegularExpression Id. */
  int PLUS = 27;
  /** RegularExpression Id. */
  int MINUS = 28;
  /** RegularExpression Id. */
  int MULTIPLY = 29;
  /** RegularExpression Id. */
  int DIVIDE = 30;
  /** RegularExpression Id. */
  int CONSTANT = 31;
  /** RegularExpression Id. */
  int DIGIT = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"go\"",
    "<INV_CMD>",
    "<TIME_CMD>",
    "<QUIT_CMD>",
    "<SAVE_CMD>",
    "<REST_CMD>",
    "<DROP_CMD>",
    "<OPEN_CMD>",
    "<TAKE_CMD>",
    "<EXAM_CMD>",
    "<PUSH_CMD>",
    "<PULL_CMD>",
    "\"say\"",
    "<NDIR>",
    "<SDIR>",
    "<EDIR>",
    "<WDIR>",
    "<UDIR>",
    "<DDIR>",
    "<ITEM_WORD>",
    "<ID_CONCEPT>",
    "\"door to the\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<CONSTANT>",
    "<DIGIT>",
    "\";\"",
    "\"(\"",
    "\")\"",
  };

}
